/**
 * Typed dev fixture for the world-loop views. Generated by
 * `pnpm gen:fixture` (client/scripts/gen-l1-fixture.ts) from the
 * frozen `data/level-1/` build. The views bind to the engine's pure
 * between-scenario operators against this seed state.
 */
import type { ItemTemplate } from '../../engine/schemas/items.ts';
import type { RecruitsFile } from '../../engine/schemas/recruits.ts';
import type { ShopCatalogFile } from '../../engine/schemas/shop-catalog.ts';
import type { ReplayEvent, UnitTemplate } from '../../engine/types.ts';
import type { WorldState } from '../../engine/world-state.ts';

import raw from './fixtures/l1.json';
import replayRaw from './fixtures/replay-l1.json';

interface Fixture {
  readonly state: WorldState;
  readonly templates: readonly UnitTemplate[];
  readonly recruits: RecruitsFile;
  readonly items: readonly ItemTemplate[];
  readonly shopCatalog: ShopCatalogFile;
}

const fx = raw as unknown as Fixture;

export const INITIAL_STATE: WorldState = fx.state;
export const TEMPLATES: readonly UnitTemplate[] = fx.templates;
export const RECRUITS: RecruitsFile = fx.recruits;
export const ITEMS: readonly ItemTemplate[] = fx.items;
export const SHOP_CATALOG: ShopCatalogFile = fx.shopCatalog;

/** A full L1 playthrough's event stream (generated by `pnpm gen:replay`),
 * for the in-scenario playback view to animate through the clock. */
export const REPLAY: readonly ReplayEvent[] = replayRaw as unknown as readonly ReplayEvent[];
