/**
 * Typed dev fixture for the world-loop views. Generated by
 * `pnpm gen:fixture` (client/scripts/gen-l1-fixture.ts) from the
 * frozen `data/level-1/` build. The views bind to the engine's pure
 * between-scenario operators against this seed state.
 */
import type { ScenarioData } from '../../engine/state.ts';
import type { ItemTemplate } from '../../engine/schemas/items.ts';
import type { RecruitsFile } from '../../engine/schemas/recruits.ts';
import type { ShopCatalogFile } from '../../engine/schemas/shop-catalog.ts';
import type { ReplayEvent, UnitTemplate } from '../../engine/types.ts';
import type { WorldState } from '../../engine/world-state.ts';

import raw from './fixtures/l1.json';
import replayRaw from './fixtures/replay-l1.json';
import scenarioL1Raw from './fixtures/scenario-l1-data.json';
import scenarioL2Raw from './fixtures/scenario-l2-data.json';

interface Fixture {
  readonly state: WorldState;
  readonly templates: readonly UnitTemplate[];
  readonly recruits: RecruitsFile;
  readonly items: readonly ItemTemplate[];
  readonly shopCatalog: ShopCatalogFile;
}

const fx = raw as unknown as Fixture;

export const INITIAL_STATE: WorldState = fx.state;
export const TEMPLATES: readonly UnitTemplate[] = fx.templates;
export const RECRUITS: RecruitsFile = fx.recruits;
export const ITEMS: readonly ItemTemplate[] = fx.items;
export const SHOP_CATALOG: ShopCatalogFile = fx.shopCatalog;

/** A full L1 playthrough's event stream (generated by `pnpm gen:replay`),
 * for the in-scenario playback view to animate through the clock. */
export const REPLAY: readonly ReplayEvent[] = replayRaw as unknown as readonly ReplayEvent[];

/**
 * Chunk B1 + B2 — per-scenario engine-data registry, indexed by
 * `scenarioIndex` (0 = L1, 1 = L2, …). Each entry is the baked
 * `ScenarioData` blob produced by `client/scripts/gen-scenarios.ts`
 * from `data/level-N/`. Adding L3+ later is one import + one array
 * entry; the runtime consumers (`useLiveScenario`, `Briefing`) look
 * up via `scenarioDataFor`.
 */
export const SCENARIO_DATA: readonly ScenarioData[] = [
  scenarioL1Raw as unknown as ScenarioData,
  scenarioL2Raw as unknown as ScenarioData,
];

/** Look up the `ScenarioData` for a given `scenarioIndex`. Returns the
 * last entry as a safe fallback for indices past the campaign (an L1
 * roster that beats every implemented scenario can still display a
 * sane briefing/board until the end-of-campaign view is built); we
 * also log to the console so the fallback path is visible during dev. */
export const scenarioDataFor = (scenarioIndex: number): ScenarioData => {
  if (scenarioIndex >= 0 && scenarioIndex < SCENARIO_DATA.length) {
    return SCENARIO_DATA[scenarioIndex]!;
  }
  // eslint-disable-next-line no-console
  console.warn(
    `scenarioDataFor: scenarioIndex ${String(scenarioIndex)} out of range ` +
      `[0, ${String(SCENARIO_DATA.length)}); falling back to last shipped scenario`,
  );
  return SCENARIO_DATA[SCENARIO_DATA.length - 1]!;
};
